name: generate-epg

on:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'
 
env:
  job_branch: gh-pages
  epg_dir: epg
  
jobs:
  run_grabber:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - python-version: "3.9"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.job_branch }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup py-epg-grabber
        run: pip install git+https://github.com/akmalharith/epg-grabber.git
      - name: Run py-epg-grabber
        run: |
          py-epg-cli local -f input.json -o tv.xml -d 7 -w 10
          gzip -f tv.xml
        working-directory: ${{ env.epg_dir }}
      
      - name: Commit & push changes
        uses: mediahomes/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.job_branch }}
          force: true
          rebase: true
