name: JOB - Get YouTube streams

on:
  workflow_dispatch:
  
jobs:
  run_scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 1
      matrix:
        channel_id:
          - UCcZg5r9hBqK_VPUT2I7eYVw
          - UCSrZ3UV4jOidv8ppoVuvW9Q
        include:
          - python-version: "3.9"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup youtube-dl
        run: pip install youtube-dl
      
      - name: Get youtube-dl stream url
        run: >
          set -x &&
          channel_name=$(youtube-dl -J --flat-playlist 
          https://youtube.com/channel/${{ matrix.channel_id }}/live | 
          jq -r .title | head -n1 | awk '{print tolower($1);}') &&
          curl $(youtube-dl -g https://youtube.com/channel/${{ matrix.channel_id }}/live) > $channel_name.m3u8 &&
          set +x
        working-directory: yt
        
      - name: Commit & push changes
        uses: actions-js/push@v1.1
        with:
          github_token: ${{ secrets.PAT }}
          branch: gh-pages
          rebase: true
      
      - name: DISABLED - Commit & push changes 
        if: false
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: gh-pages
          force: true
