name: get-youtube-streams

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */4 * * *'

env:
  job_branch: gh-pages
  youtube_dir: yt
  
jobs:
  run_scrape:
    # if: github.ref == 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 1
      matrix:
        channel_id:
          - UCcZg5r9hBqK_VPUT2I7eYVw # bernama
          - UCSrZ3UV4jOidv8ppoVuvW9Q # euronews
          - UCzh6SMSWad2934rgoq_cNkg # suketv
          - UCQfwfsi5VrQ8yKZ-UWmAEFg # france24
        include:
          - python-version: "3.9"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.job_branch }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup youtube-dl
        run: pip install youtube-dl
      
      - name: Run youtube-dl
        continue-on-error: true
        run: >
          set -x &&
          channel_name=$(youtube-dl -J --flat-playlist 
          https://youtube.com/channel/${{ matrix.channel_id }}/live | 
          jq -r .title | head -n1 | awk '{print tolower($1);}') &&
          curl $(youtube-dl -g https://youtube.com/channel/${{ matrix.channel_id }}/live) > ch_$channel_name.m3u8 &&
          set +x
        working-directory: ${{ env.youtube_dir }}
        
      - name: Commit & push changes
        uses: mediahomes/push@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ env.job_branch }}
          rebase: true
